#==============================================================================#
# Author: 
# Date: 19.02.2019
# Comments:
# Neuroblastoma Supe Enhancer Landscape code
# 
# INPUT:
# main_working_directory/
# ├── data/
# │   ├── cells/
# │   │   ├── chipseq/
# │   │   │   ├── H3K27ac/
# │   │   │   └── H3K4me3/
# │   │   ├── rnaseq/
# │   └── tumor/
# │       ├── chipseq
# │       │   ├── H3K27ac/
# │       │   └── H3K4me3/
# │       ├── rnaseq/
# ├── analysis/
# └── results/
#     ├── figure_1/
#     ├── figure_2/
#     ├── figure_3/
#     ├── figure_4/
#     ├── sup_figure_1/
#     ├── sup_figure_2/
#     ├── sup_figure_3/
#     ├── sup_figure_4/
#     ├── sup_table_1/
#     ├── sup_table_2/
#     ├── sup_table_3/
#     ├── sup_table_4/
#==============================================================================#
### SAMPLE Info - REQUIRED PARAMETERS ####
tumor_annotation_csv: /icgc/dkfzlsdf/analysis/B080/crg/B087_Neuroblastoma/publication_GEO/annotation/annotation_tumors.csv
cells_annotation_csv: /icgc/dkfzlsdf/analysis/B080/crg/B087_Neuroblastoma/publication_GEO/annotation/annotation_cells.csv
#tumor_annotation_csv: /net/data.isilon/ag-cherrmann/hdsu/projects/neuroblastoma/publication_GEO/annotation/annotation_tumors.csv
#cells_annotation_csv: /net/data.isilon/ag-cherrmann/hdsu/projects/neuroblastoma/publication_GEO/annotation/annotation_cells.csv



# Paths to data and results
main_working_directory: /icgc/dkfzlsdf/analysis/B080/crg/B087_Neuroblastoma/publication_GEO/
#main_working_directory: /net/data.isilon/ag-cherrmann/hdsu/projects/neuroblastoma/publication_GEO/


#==============================================================================#
#                         Pipeline Steps to Run                                #
#==============================================================================#
consensusSE:
    call_consensus_tumor_SE: True
