#==============================================================================#
# Author: 
# Date: 19.02.2019
# Comments:
# Neuroblastoma Supe Enhancer Landscape code
# 
# INPUT:
# main_working_directory/
# ├── data/
# │   ├── cells/
# │   │   ├── chipseq/
# │   │   │   ├── H3K27ac/
# │   │   │   └── H3K4me3/
# │   │   ├── rnaseq/
# │   └── tumor/
# │       ├── chipseq
# │       │   ├── H3K27ac/
# │       │   └── H3K4me3/
# │       ├── rnaseq/
# ├── analysis/
# └── results/
#     ├── figure_1/
#     ├── figure_2/
#     ├── figure_3/
#     ├── figure_4/
#     ├── sup_figure_1/
#     ├── sup_figure_2/
#     ├── sup_figure_3/
#     ├── sup_figure_4/
#     ├── sup_table_1/
#     ├── sup_table_2/
#     ├── sup_table_3/
#     ├── sup_table_4/
#==============================================================================#
### SAMPLE Info - REQUIRED PARAMETERS ####
tumor_annotation_csv: /icgc/dkfzlsdf/analysis/B080/crg/B087_Neuroblastoma/publication_GEO/annotation/annotation_tumor.csv
cells_annotation_csv: /icgc/dkfzlsdf/analysis/B080/crg/B087_Neuroblastoma/publication_GEO/annotation/annotation_cells.csv
#tumor_annotation_csv: /net/data.isilon/ag-cherrmann/hdsu/projects/neuroblastoma/publication_GEO/annotation/annotation_tumors.csv
#cells_annotation_csv: /net/data.isilon/ag-cherrmann/hdsu/projects/neuroblastoma/publication_GEO/annotation/annotation_cells.csv



# Paths to data and results
main_working_directory: /icgc/dkfzlsdf/analysis/B080/crg/B087_Neuroblastoma/publication_GEO/
#main_working_directory: /net/data.isilon/ag-cherrmann/hdsu/projects/neuroblastoma/publication_GEO/


#==============================================================================#
#                         Pipeline Steps to Run                                #
#==============================================================================#
phase01_consensusSE:
    consensus_tumor_SE : True
    SE_target_gene     : True

phase02_NMF:
    NMF_chipseq : True
    NMF_rnaseq  : True

phase03_ARACNe:
    input_matrix : True
    run_ARACNe   : True
    run_VIPER    : True

    
compileFigs:
  figure1    : True
  figure2    : True
  figure3    : True
  figure4    : True
  sup_figure2: True



#==============================================================================#
#                                NMF parameters                                #
#==============================================================================#
# Parameters to run Non-Negative Matrix Factorization
# k.min: minimum number of signatures to decompose
# k.max: maximun number of signatures to decompose
# Iterations: number of outer iterations to run

# Select NMF optimal K for each assay after first run

NMFparams:
    tumor:  
        k.min      : 2
        k.max      : 6
        iterations : 50
        optimalK:
            chipseq: 4
            rnaseq : 4
    cells: 
        k.min      : 2
        k.max      : 6
        iterations : 50
        optimalK:
            chipseq: 3
            rnaseq : 4
    tumor_cells:  
        k.min      : 2
        k.max      : 6
        iterations : 100
        optimalK:
            chipseq: 5
            rnaseq : 5


#==============================================================================#
#                                ARACNE-AP                                     #
#==============================================================================#
ARACNe:
  mi_pval_cutoff           : 1E-8
  consolidation_pval_cutoff: 1E-3
  cpus                     : 10



#==============================================================================#
#                              IGV plots regions                               #
#==============================================================================#
igv_plot:
  figure1e:
    chr   : chr4
    start : 140500000
    end   : 141270000
    name  : MAML3
    window: 2000
    ymax  : max
    width : 11
    height: 6
  figure3_CCND1:
    chr   : chr11
    start : 68776977
    end   : 69667477
    name  : CCND1
    window: 3000
    width : 8
    height: 6
  figure4i:
    chr   : chr12
    start : 64910000
    end   : 65100000
    name  : RASSF3
    window: 2000
    ymax  : 35
    width : 8
    height: 6
    

